{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "{{ .Values.istio.gateway.host }}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.istio.virtualservice.name }}
spec:
  hosts:
  - "{{ .Values.istio.gateway.host }}"
  gateways:
  - {{ .Values.istio.gateway.name }}
  http:
  - route:
    - destination:
        host: {{ include "myapp-chart.fullname" . }}
        subset: {{ .Values.istio.version }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.istio.destinationrule.name }}
spec:
  host: {{ include "myapp-chart.fullname" . }}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
{{- end }}
